/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motorph.UserManagement;

import Frames.EmployeeMainFrame;
import com.mycompany.motorph.UserManagement.LogIn.EmployeeLogIn;
import com.opencsv.exceptions.CsvValidationException;
import java.io.IOException;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Frames.MainFrame;


/**
 *
 * @author trishameiatienza
 */
public class EmployeeLogInFrame extends javax.swing.JFrame {

    public EmployeeLogInFrame() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitbtn1 = new javax.swing.JButton();
        usernametf1 = new javax.swing.JTextField();
        loginbtn1 = new javax.swing.JButton();
        pwtf1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbtn1.setBackground(new java.awt.Color(223, 163, 197));
        exitbtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitbtn1.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn1.setText("?");
        exitbtn1.setBorder(null);
        exitbtn1.setBorderPainted(false);
        exitbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtn1Exit(evt);
            }
        });
        exitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 336, 20, -1));

        usernametf1.setBackground(new java.awt.Color(246, 245, 244));
        usernametf1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernametf1.setBorder(null);
        usernametf1.setCaretColor(new java.awt.Color(102, 102, 102));
        usernametf1.setSelectionColor(new java.awt.Color(62, 149, 230));
        usernametf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametf1ActionPerformed(evt);
            }
        });
        jPanel1.add(usernametf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 260, 32));

        loginbtn1.setBackground(new java.awt.Color(250, 190, 44));
        loginbtn1.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        loginbtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn1.setText("Log In");
        loginbtn1.setBorder(null);
        loginbtn1.setBorderPainted(false);
        loginbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtn1MouseClicked(evt);
            }
        });
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 392, 265, 32));

        pwtf1.setBackground(new java.awt.Color(246, 245, 244));
        pwtf1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pwtf1.setToolTipText("Password");
        pwtf1.setBorder(null);
        pwtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwtf1ActionPerformed(evt);
            }
        });
        jPanel1.add(pwtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 292, 260, 30));

        jButton1.setBackground(new java.awt.Color(246, 245, 244));
        jButton1.setFont(new java.awt.Font("Thonburi", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Sign in as Admin");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 210, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/trishameiatienza/Documents/GitHub/OOPMS2/motorph-oop-master/src/main/java/com/mycompany/OOP/UserManagement/Login as Employee.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Assuming EmployeeLogInFrame is another JFrame that needs to be shown.
    LogInFrame LoginFrame = new LogInFrame();
    LoginFrame.setVisible(true);
    
    // Optionally, if you want to hide or dispose the current LoginFrame, you can call:
     this.dispose(); // to close the current frame
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitbtn1Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtn1Exit
        JOptionPane.showMessageDialog(null, "Contact through email");
    }//GEN-LAST:event_exitbtn1Exit

    private void exitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtn1ActionPerformed

    private void usernametf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametf1ActionPerformed

    private void loginbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MouseClicked
        LogIn login = new LogIn();
        login.setusername(usernametf1.getText());
        login.setpassword(pwtf1.getPassword());

        try {
            if(login.isAuthenticated()){
                //*JOptionPane.showMessageDialog(this, "Login Successful!");
                dispose();//
                //setVisible(false);
                MainFrame mainframe = new MainFrame();
                mainframe.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Username or Password is incorrect. Try Again.", "Invalid Credentials", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(LogInFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginbtn1MouseClicked

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtn1ActionPerformed

    private void pwtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwtf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JPasswordField pwtf1;
    private javax.swing.JTextField usernametf1;
    // End of variables declaration//GEN-END:variables
}
